### ISSUE TITLE
얘를 2016 스터디 레포지토리로 써도 됩니까?

### ISSUE THREAD

**Issue by benjioh5** [HYU-ICEWALL/STUDY2016#6]
2016 1학기, 여름, 2학기, 겨울에 있었던/있을 스터디들 내용을 하나로 꽁쳐박아넣으려고 하는데, 이 레포를 사용하고 싶습니다. 가능한지 회신부탁드립니다.

**Comment by jiunbae** [comment]
전 그냥 썼었는데

**Comment by jiunbae** [comment]
마스터로 올려드릴까요?

**Comment by benjioh5** [comment]
ㄱㅅㄱㅅ
